// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `index_slot`, `rating_from_code`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// واژه‌نامه را می‌سازد. Call once at startup, then again only if the content
/// pack changes.
Future<int> buildIndex({required List<WordRow> rows}) =>
    SarehRust.instance.api.crateApiBuildIndex(rows: rows);

/// جست‌وجو. Returns an empty list if the index has not been built yet, rather
/// than failing — the UI shows "هنوز واژه‌ای نیست" either way.
Future<List<SearchHit>> searchWords(
        {required String query, required int limit}) =>
    SarehRust.instance.api.crateApiSearchWords(query: query, limit: limit);

/// نرمال‌سازیِ متنِ فارسی برای نمایش و ذخیره.
Future<String> normalizeText({required String input}) =>
    SarehRust.instance.api.crateApiNormalizeText(input: input);

/// آیا پاسخِ تایپ‌شده با پاسخِ درست یکی است؟
Future<bool> answersMatch({required String typed, required String expected}) =>
    SarehRust.instance.api
        .crateApiAnswersMatch(typed: typed, expected: expected);

/// اعداد پارسی برای نمایش.
Future<String> persianDigits({required String input}) =>
    SarehRust.instance.api.crateApiPersianDigits(input: input);

/// درجه‌بندی از روی رفتار، نه از روی خودسنجی.
Future<int> rateAnswer(
        {required bool correct,
        required int answerMs,
        required bool hesitated}) =>
    SarehRust.instance.api.crateApiRateAnswer(
        correct: correct, answerMs: answerMs, hesitated: hesitated);

/// نخستین دیدارِ واژه.
Future<ReviewOutcome> scheduleFirst(
        {required int ratingCode, required double desiredRetention}) =>
    SarehRust.instance.api.crateApiScheduleFirst(
        ratingCode: ratingCode, desiredRetention: desiredRetention);

/// مرورِ بعدی.
Future<ReviewOutcome> scheduleReview(
        {required ReviewState state,
        required double elapsedDays,
        required int ratingCode,
        required double desiredRetention}) =>
    SarehRust.instance.api.crateApiScheduleReview(
        state: state,
        elapsedDays: elapsedDays,
        ratingCode: ratingCode,
        desiredRetention: desiredRetention);

/// بازیابی‌پذیری — درصدِ احتمالِ به‌یادآوردن، برای نوارِ «آمادگی» در نمایه.
Future<double> retrievability(
        {required ReviewState state, required double elapsedDays}) =>
    SarehRust.instance.api
        .crateApiRetrievability(state: state, elapsedDays: elapsedDays);

/// خروجیِ زمان‌بندی در سویِ Dart.
class ReviewOutcome {
  final double stability;
  final double difficulty;
  final int intervalDays;

  const ReviewOutcome({
    required this.stability,
    required this.difficulty,
    required this.intervalDays,
  });

  @override
  int get hashCode =>
      stability.hashCode ^ difficulty.hashCode ^ intervalDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewOutcome &&
          runtimeType == other.runtimeType &&
          stability == other.stability &&
          difficulty == other.difficulty &&
          intervalDays == other.intervalDays;
}

/// حالت حافظه در سویِ Dart.
class ReviewState {
  final double stability;
  final double difficulty;

  const ReviewState({
    required this.stability,
    required this.difficulty,
  });

  @override
  int get hashCode => stability.hashCode ^ difficulty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewState &&
          runtimeType == other.runtimeType &&
          stability == other.stability &&
          difficulty == other.difficulty;
}

/// A search result as Dart gets it back.
class SearchHit {
  final String id;

  /// "sare" | "loan" | "english"
  final String field;
  final int score;

  const SearchHit({
    required this.id,
    required this.field,
    required this.score,
  });

  @override
  int get hashCode => id.hashCode ^ field.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          field == other.field &&
          score == other.score;
}

/// A dictionary row as Dart sends it in.
class WordRow {
  final String id;
  final String sare;
  final String loan;
  final String english;

  const WordRow({
    required this.id,
    required this.sare,
    required this.loan,
    required this.english,
  });

  @override
  int get hashCode =>
      id.hashCode ^ sare.hashCode ^ loan.hashCode ^ english.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sare == other.sare &&
          loan == other.loan &&
          english == other.english;
}
