// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class SarehRust
    extends BaseEntrypoint<SarehRustApi, SarehRustApiImpl, SarehRustWire> {
  @internal
  static final instance = SarehRust._();

  SarehRust._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    SarehRustApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required SarehRustApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<SarehRustApiImpl, SarehRustWire> get apiImplConstructor =>
      SarehRustApiImpl.new;

  @override
  WireConstructor<SarehRustWire> get wireConstructor =>
      SarehRustWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1787716574;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'sareh_core',
    ioDirectory: '../core/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class SarehRustApi extends BaseApi {
  Future<bool> crateApiAnswersMatch(
      {required String typed, required String expected});

  Future<int> crateApiBuildIndex({required List<WordRow> rows});

  Future<String> crateApiNormalizeText({required String input});

  Future<String> crateApiPersianDigits({required String input});

  Future<int> crateApiRateAnswer(
      {required bool correct, required int answerMs, required bool hesitated});

  Future<double> crateApiRetrievability(
      {required ReviewState state, required double elapsedDays});

  Future<ReviewOutcome> crateApiScheduleFirst(
      {required int ratingCode, required double desiredRetention});

  Future<ReviewOutcome> crateApiScheduleReview(
      {required ReviewState state,
      required double elapsedDays,
      required int ratingCode,
      required double desiredRetention});

  Future<List<SearchHit>> crateApiSearchWords(
      {required String query, required int limit});
}

class SarehRustApiImpl extends SarehRustApiImplPlatform
    implements SarehRustApi {
  SarehRustApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiAnswersMatch(
      {required String typed, required String expected}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(typed, serializer);
        sse_encode_String(expected, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAnswersMatchConstMeta,
      argValues: [typed, expected],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAnswersMatchConstMeta => const TaskConstMeta(
        debugName: "answers_match",
        argNames: ["typed", "expected"],
      );

  @override
  Future<int> crateApiBuildIndex({required List<WordRow> rows}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_word_row(rows, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiBuildIndexConstMeta,
      argValues: [rows],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBuildIndexConstMeta => const TaskConstMeta(
        debugName: "build_index",
        argNames: ["rows"],
      );

  @override
  Future<String> crateApiNormalizeText({required String input}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(input, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiNormalizeTextConstMeta,
      argValues: [input],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNormalizeTextConstMeta => const TaskConstMeta(
        debugName: "normalize_text",
        argNames: ["input"],
      );

  @override
  Future<String> crateApiPersianDigits({required String input}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(input, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPersianDigitsConstMeta,
      argValues: [input],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPersianDigitsConstMeta => const TaskConstMeta(
        debugName: "persian_digits",
        argNames: ["input"],
      );

  @override
  Future<int> crateApiRateAnswer(
      {required bool correct, required int answerMs, required bool hesitated}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(correct, serializer);
        sse_encode_u_32(answerMs, serializer);
        sse_encode_bool(hesitated, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_8,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiRateAnswerConstMeta,
      argValues: [correct, answerMs, hesitated],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRateAnswerConstMeta => const TaskConstMeta(
        debugName: "rate_answer",
        argNames: ["correct", "answerMs", "hesitated"],
      );

  @override
  Future<double> crateApiRetrievability(
      {required ReviewState state, required double elapsedDays}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_review_state(state, serializer);
        sse_encode_f_64(elapsedDays, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiRetrievabilityConstMeta,
      argValues: [state, elapsedDays],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRetrievabilityConstMeta => const TaskConstMeta(
        debugName: "retrievability",
        argNames: ["state", "elapsedDays"],
      );

  @override
  Future<ReviewOutcome> crateApiScheduleFirst(
      {required int ratingCode, required double desiredRetention}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_8(ratingCode, serializer);
        sse_encode_f_64(desiredRetention, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_review_outcome,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiScheduleFirstConstMeta,
      argValues: [ratingCode, desiredRetention],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiScheduleFirstConstMeta => const TaskConstMeta(
        debugName: "schedule_first",
        argNames: ["ratingCode", "desiredRetention"],
      );

  @override
  Future<ReviewOutcome> crateApiScheduleReview(
      {required ReviewState state,
      required double elapsedDays,
      required int ratingCode,
      required double desiredRetention}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_review_state(state, serializer);
        sse_encode_f_64(elapsedDays, serializer);
        sse_encode_u_8(ratingCode, serializer);
        sse_encode_f_64(desiredRetention, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_review_outcome,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiScheduleReviewConstMeta,
      argValues: [state, elapsedDays, ratingCode, desiredRetention],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiScheduleReviewConstMeta => const TaskConstMeta(
        debugName: "schedule_review",
        argNames: ["state", "elapsedDays", "ratingCode", "desiredRetention"],
      );

  @override
  Future<List<SearchHit>> crateApiSearchWords(
      {required String query, required int limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        sse_encode_u_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_search_hit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSearchWordsConstMeta,
      argValues: [query, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchWordsConstMeta => const TaskConstMeta(
        debugName: "search_words",
        argNames: ["query", "limit"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ReviewState dco_decode_box_autoadd_review_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_review_state(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SearchHit> dco_decode_list_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_hit).toList();
  }

  @protected
  List<WordRow> dco_decode_list_word_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_word_row).toList();
  }

  @protected
  ReviewOutcome dco_decode_review_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ReviewOutcome(
      stability: dco_decode_f_64(arr[0]),
      difficulty: dco_decode_f_64(arr[1]),
      intervalDays: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  ReviewState dco_decode_review_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ReviewState(
      stability: dco_decode_f_64(arr[0]),
      difficulty: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  SearchHit dco_decode_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SearchHit(
      id: dco_decode_String(arr[0]),
      field: dco_decode_String(arr[1]),
      score: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WordRow dco_decode_word_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WordRow(
      id: dco_decode_String(arr[0]),
      sare: dco_decode_String(arr[1]),
      loan: dco_decode_String(arr[2]),
      english: dco_decode_String(arr[3]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ReviewState sse_decode_box_autoadd_review_state(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_review_state(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SearchHit> sse_decode_list_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchHit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_hit(deserializer));
    }
    return ans_;
  }

  @protected
  List<WordRow> sse_decode_list_word_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WordRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_word_row(deserializer));
    }
    return ans_;
  }

  @protected
  ReviewOutcome sse_decode_review_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stability = sse_decode_f_64(deserializer);
    var var_difficulty = sse_decode_f_64(deserializer);
    var var_intervalDays = sse_decode_u_32(deserializer);
    return ReviewOutcome(
        stability: var_stability,
        difficulty: var_difficulty,
        intervalDays: var_intervalDays);
  }

  @protected
  ReviewState sse_decode_review_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stability = sse_decode_f_64(deserializer);
    var var_difficulty = sse_decode_f_64(deserializer);
    return ReviewState(stability: var_stability, difficulty: var_difficulty);
  }

  @protected
  SearchHit sse_decode_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_field = sse_decode_String(deserializer);
    var var_score = sse_decode_u_32(deserializer);
    return SearchHit(id: var_id, field: var_field, score: var_score);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WordRow sse_decode_word_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sare = sse_decode_String(deserializer);
    var var_loan = sse_decode_String(deserializer);
    var var_english = sse_decode_String(deserializer);
    return WordRow(
        id: var_id, sare: var_sare, loan: var_loan, english: var_english);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_review_state(
      ReviewState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_review_state(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_search_hit(
      List<SearchHit> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_hit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_word_row(List<WordRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_word_row(item, serializer);
    }
  }

  @protected
  void sse_encode_review_outcome(ReviewOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.stability, serializer);
    sse_encode_f_64(self.difficulty, serializer);
    sse_encode_u_32(self.intervalDays, serializer);
  }

  @protected
  void sse_encode_review_state(ReviewState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.stability, serializer);
    sse_encode_f_64(self.difficulty, serializer);
  }

  @protected
  void sse_encode_search_hit(SearchHit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.field, serializer);
    sse_encode_u_32(self.score, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_word_row(WordRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.sare, serializer);
    sse_encode_String(self.loan, serializer);
    sse_encode_String(self.english, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
