// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class SarehRustApiImplPlatform extends BaseApiImpl<SarehRustWire> {
  SarehRustApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ReviewState dco_decode_box_autoadd_review_state(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SearchHit> dco_decode_list_search_hit(dynamic raw);

  @protected
  List<WordRow> dco_decode_list_word_row(dynamic raw);

  @protected
  ReviewOutcome dco_decode_review_outcome(dynamic raw);

  @protected
  ReviewState dco_decode_review_state(dynamic raw);

  @protected
  SearchHit dco_decode_search_hit(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WordRow dco_decode_word_row(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ReviewState sse_decode_box_autoadd_review_state(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SearchHit> sse_decode_list_search_hit(SseDeserializer deserializer);

  @protected
  List<WordRow> sse_decode_list_word_row(SseDeserializer deserializer);

  @protected
  ReviewOutcome sse_decode_review_outcome(SseDeserializer deserializer);

  @protected
  ReviewState sse_decode_review_state(SseDeserializer deserializer);

  @protected
  SearchHit sse_decode_search_hit(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WordRow sse_decode_word_row(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_review_state(
      ReviewState self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_search_hit(
      List<SearchHit> self, SseSerializer serializer);

  @protected
  void sse_encode_list_word_row(List<WordRow> self, SseSerializer serializer);

  @protected
  void sse_encode_review_outcome(ReviewOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_review_state(ReviewState self, SseSerializer serializer);

  @protected
  void sse_encode_search_hit(SearchHit self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_word_row(WordRow self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class SarehRustWire implements BaseWire {
  SarehRustWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external SarehRustWasmModule get wasmModule;

@JS()
@anonymous
extension type SarehRustWasmModule._(JSObject _) implements JSObject {}
